services: 
  flaskapp:
    build: .
    ports: 
      - "5000:5000"
    environment: 
      DB_HOST: db 
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      db: 
        condition: service_healthy
    networks: 
      - three-tier    


  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME} 
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "mysqladmin ping -h localhost -uroot -p$${DB_PASSWORD} --silent"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - three-tier     
 
volumes: 
  mysql_data: 

networks:
  three-tier: 
    
    
   
      